# Generated by Django 3.0.2 on 2020-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='<No Title :3>', max_length=200)),
                ('author', models.CharField(default='<No Author :3>', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
